// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCSzPvxsTz9jHwaYaK6Yqcr41-3P5qF4uU',
    appId: '1:519577135692:web:9a2111af19881abf7aa2e9',
    messagingSenderId: '519577135692',
    projectId: 'anvadhi-60f01',
    authDomain: 'anvadhi-60f01.firebaseapp.com',
    storageBucket: 'anvadhi-60f01.appspot.com',
    measurementId: 'G-N9DW6BLXKS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-DJxIzpvRBe0YtFxW8ttu-Qbp6I4xJUY',
    appId: '1:519577135692:android:ab451bc3af516e177aa2e9',
    messagingSenderId: '519577135692',
    projectId: 'anvadhi-60f01',
    storageBucket: 'anvadhi-60f01.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-B1VxcYSBS3Mpu42FyReRu0S_ZdGOEu4',
    appId: '1:519577135692:ios:e589c1c73a8dee387aa2e9',
    messagingSenderId: '519577135692',
    projectId: 'anvadhi-60f01',
    storageBucket: 'anvadhi-60f01.appspot.com',
    iosClientId: '519577135692-reveho0ibg5qaau6dkrvfrvhevccjbmk.apps.googleusercontent.com',
    iosBundleId: 'com.iittp.anvadhi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD-B1VxcYSBS3Mpu42FyReRu0S_ZdGOEu4',
    appId: '1:519577135692:ios:1383db84cd825e8f7aa2e9',
    messagingSenderId: '519577135692',
    projectId: 'anvadhi-60f01',
    storageBucket: 'anvadhi-60f01.appspot.com',
    iosClientId: '519577135692-tg850q09ctpatjanm6i8ajbv2o5e62hl.apps.googleusercontent.com',
    iosBundleId: 'com.iittp.anvadhi.RunnerTests',
  );
}
